config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'Account', at: 'auth', controllers: {
    omniauth_callbacks: 'account/auth_callbacks',
  }

  get 'auth/confirmation/success' => 'account/auth_callbacks#confirmation_success'
  get 'auth/password/reset' => 'account/auth_callbacks#reset_password'
  post 'chat' => 'chats#chat', constraints: { format: :xml }
  get 'chat' => 'chats#configuration'

  namespace :account, format: true, constraints: { format: :json } do
    post ':account_id/cellphone' => 'cellphones#create' 
    post ':account_id/cellphone/:id' => 'cellphones#resend'
    put ':account_id/cellphone/:id' => 'cellphones#update' 
  end

  resources :merchants, only: [:show, :update], module: :merchants, 
    format: true, constraints: { format: :json } do
    resources :dropoffs, format: true, only: [:index, :create]

    resources :restaurants, only: [:index, :create] do
      resources :caterings, only: :create

      resources :dishes, only: :create

      resources :combos, only: :create
      get 'combos/recent' => 'combos#recent'
    end

    resources :shippings, only: [:create, :update, :destroy] do
      member do
        get 'list_orders' => 'shippings#list_orders'
        put 'update_state' => 'shippings#update_state'
      end
    end

    resources :dishes, only: [:destroy, :update]

    resources :combos, only: [:destroy, :update, :show]

    resources :uploads, only: :create

    resources :debts, only: :index

    resources :transactions, only: [:index, :update, :destroy]
    get 'transactions/pending' => 'transactions#pending'

    put 'orders/:id/approve' => 'orders#approve'
    put 'orders/:id/pickup' => 'orders#pickup'
  end

  namespace :merchant, format: true, constraints: { format: :json } do
    resources :dropoffs, only: :destroy
    resources :restaurants, only: [:update, :destroy, :new]
  end
  
  resources :customers, module: :customers, format: true, 
    constraints: { format: :json } do
    resources :orders, only: [:index, :show]
    resources :combo_orders, only: [:create]
    resources :dish_orders, only: [:create]
    put 'orders/recent' => 'orders#recent'
    put 'orders/:id/cancel' => 'orders#cancel' 

    resources :payments, only: [:create, :destroy, :show, :index]
    resources :qr_codes, only: :new
  end

  resources :restaurants, module: :restaurant, only: :show, 
    format: true, constraints: { format: :json }do

    resources :dishes, only: :index

    resources :combos, only: :index

    resources :caterings, only: :index
    get 'caterings/recent' => 'caterings#recent'
  end

  namespace :restaurant, format: true, 
    constraints: { format: :json } do
    resources :caterings, only: :show

    resources :combos, only: :show

    resources :dishes, only: :show

    get 'new' => 'restaurants#new'
  end

  resources :locations, format: true, 
    constraints: { format: :json } do
    collection do
      get 'query'
    end
  end
  
  get 'buildings/coord' => 'buildings#query_by_coord', format: true, 
    constraints: { format: :json }
  get 'buildings/city_company' => 'buildings#query_by_city_company', 
    format: true, constraints: { format: :json }
  get 'buildings/address_name' => 'buildings#fuzzy_query_by_address_name', 
    format: true, constraints: { format: :json }

  resources :companies, only: :index, format: true, 
    constraints: { format: :json }
  get 'companies/:name' => 'companies#query', format: true, 
    constraints: { format: :json }
  
  resources :uploads, only: :create, format: true, 
    constraints: { format: :json }

end

app/models/cellphone.rb
require 'securerandom'
class Cellphone < ActiveRecord::Base
  validates :number, presence: true, uniqueness: { message: I18n.t('error.NUMBER_USED') }, number: true

  CONFIRMATION_LIFESPAN = 200
  MIN_CONFIRMATION_SEND_INVERTAL = 60
  CONFIRMATION_TOKEN_LENGTH = 6

  def self.create_cellphone(number, account_id)
    cellphone = Cellphone.new account_id: account_id, number: number
    cellphone.send_confirmation
    cellphone.save!
    cellphone.confirmation_token
  end

  def send_confirmation
    self.generate_cellphone_confirmation_token
  end

  def resend_confirmation
    if self.confirmation_sent_at + \
      MIN_CONFIRMATION_SEND_INVERTAL.second > Time.now
      self.errors[:confirm] = I18n.t 'error.RESEND_TOO_FREQUENTLY'
      raise Exceptions::NotEffective.new(self)
    elsif self.has_confirmed?
      self.errors[:confirm] = I18n.t 'error.DUPLICATE_CONFIRMATION'
      raise Exceptions::NotEffective.new(self)
    end
    return self.generate_cellphone_confirmation_token
  end

  def verify_token(token, account)
    if self.has_confirmed?
      errors = I18n.t 'error.DUPLICATE_CONFIRMATION'
    elsif self.has_confirmation_expired? 
      errors = I18n.t 'error.CONFIRMATION_EXPIRED'
    elsif !self.token_valid? token
      errors = I18n.t 'error.WRONG_TOKEN'
    end
    unless errors.nil?
      self.errors[:confirm] = errors
      raise Exceptions::NotEffective.new(self)
    end
    Cellphone.transaction do
      self.verify!
      account.update_attribute :cellphone_id, self.id
    end
  end

  def has_confirmation_expired?
    return (self.confirmation_sent_at +
      CONFIRMATION_LIFESPAN.second) < Time.now
  end

  protected

    def has_confirmed?
      return self.confirmed_at.present?
    end

    def token_valid?(token)
      return confirmation_token == token
    end

    def verify!
      self.update_attribute(:confirmed_at, Time.now.utc)
    end
  
    def generate_cellphone_confirmation_token
      token = ""
      CONFIRMATION_TOKEN_LENGTH.times do
        token << SecureRandom.random_number(10).to_s
      end
      puts "TOKEN GENERATED IS: " + token
      self.confirmation_token = token
      self.confirmation_sent_at = Time.now.utc
    end
end

app/controllers/account/cellphones_controller.rb
class Account::CellphonesController < WebApplicationController
  
  def create
    token = Cellphone.create_cellphone @number, @account.id
    render json: Response::JsonResponse.new(token)
  end

  def resend
    token = @cellphone.resend_confirmation
    render json: Response::JsonResponse.new(token)
  end

  def update
    @cellphone.verify_token @token, @account
    render nothing: true
  end
  
  private

    def params_sanitization
      sanitize :create, account_id: :account, number: :number
      sanitize :resend, account_id: :account, id: :cellphone
      sanitize :update, account_id: :account,id: :cellphone, token: :confirmation_token
    end

    def authorization
      authorize :create do
        current_account.id == @account.id
      end
      authorize [:resend, :update] do
        current_account.id == @account.id && \
          @cellphone.account_id == @account.id
      end
    end
end

app/helpers/cellphones_helper.rb
module CellphonesHelper
  def new_registration_path
    return session[:type] == 'users' ? new_user_registration_path
    : new_merchant_registration_path
  end
end

app/views/cellphones/_form.html.erb
<%= form_for(@cellphone) do |f| %>
  <% if @cellphone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cellphone.errors.count, "error") %> prohibited this cellphone from being saved:</h2>

      <ul>
      <% @cellphone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cellphones/create.js.erb
<% if not @redirect %>
  $("#message").html("<%= escape_javascript(render 'layouts/messages').html_safe %>");
<% else %>
  window.location = "<%= new_account_registration_path %>"
<% end %>

app/views/cellphones/edit.html.erb
<h1>Editing Cellphone</h1>

<%= render 'form' %>

<%= link_to 'Show', @cellphone %> |
<%= link_to 'Back', cellphones_path %>

app/views/cellphones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cellphones</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cellphones.each do |cellphone| %>
      <tr>
        <td><%= link_to 'Show', cellphone %></td>
        <td><%= link_to 'Edit', edit_cellphone_path(cellphone) %></td>
        <td><%= link_to 'Destroy', cellphone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cellphone', new_cellphone_path %>

app/views/cellphones/new.html.erb
<h1>New Cellphone</h1>

<%= form_for @cellphone, remote: true do |f|%>
  <%= f.label :cellphone_number %><br />
  <%= f.text_field :number, autofocus: true %><br />
  <%= f.submit 'Send Confirmation', name: 'send' %><br />
  <%= f.label :confirmation_token %><br />
  <%= f.text_field :confirmation_token, autofocus: true %><br />
  <%= f.submit 'Verify', name: 'verify' %>
<% end %>

app/views/cellphones/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cellphone_path(@cellphone) %> |
<%= link_to 'Back', cellphones_path %>