config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'Account', at: 'auth', controllers: {
    omniauth_callbacks: 'account/auth_callbacks',
  }

  get 'auth/confirmation/success' => 'account/auth_callbacks#confirmation_success'
  get 'auth/password/reset' => 'account/auth_callbacks#reset_password'
  post 'chat' => 'chats#chat', constraints: { format: :xml }
  get 'chat' => 'chats#configuration'

  namespace :account, format: true, constraints: { format: :json } do
    post ':account_id/cellphone' => 'cellphones#create' 
    post ':account_id/cellphone/:id' => 'cellphones#resend'
    put ':account_id/cellphone/:id' => 'cellphones#update' 
  end

  resources :merchants, only: [:show, :update], module: :merchants, 
    format: true, constraints: { format: :json } do
    resources :dropoffs, format: true, only: [:index, :create]

    resources :restaurants, only: [:index, :create] do
      resources :caterings, only: :create

      resources :dishes, only: :create

      resources :combos, only: :create
      get 'combos/recent' => 'combos#recent'
    end

    resources :shippings, only: [:create, :update, :destroy] do
      member do
        get 'list_orders' => 'shippings#list_orders'
        put 'update_state' => 'shippings#update_state'
      end
    end

    resources :dishes, only: [:destroy, :update]

    resources :combos, only: [:destroy, :update, :show]

    resources :uploads, only: :create

    resources :debts, only: :index

    resources :transactions, only: [:index, :update, :destroy]
    get 'transactions/pending' => 'transactions#pending'

    put 'orders/:id/approve' => 'orders#approve'
    put 'orders/:id/pickup' => 'orders#pickup'
  end

  namespace :merchant, format: true, constraints: { format: :json } do
    resources :dropoffs, only: :destroy
    resources :restaurants, only: [:update, :destroy, :new]
  end
  
  resources :customers, module: :customers, format: true, 
    constraints: { format: :json } do
    resources :orders, only: [:index, :show]
    resources :combo_orders, only: [:create]
    resources :dish_orders, only: [:create]
    put 'orders/recent' => 'orders#recent'
    put 'orders/:id/cancel' => 'orders#cancel' 

    resources :payments, only: [:create, :destroy, :show, :index]
    resources :qr_codes, only: :new
  end

  resources :restaurants, module: :restaurant, only: :show, 
    format: true, constraints: { format: :json }do

    resources :dishes, only: :index

    resources :combos, only: :index

    resources :caterings, only: :index
    get 'caterings/recent' => 'caterings#recent'
  end

  namespace :restaurant, format: true, 
    constraints: { format: :json } do
    resources :caterings, only: :show

    resources :combos, only: :show

    resources :dishes, only: :show

    get 'new' => 'restaurants#new'
  end

  resources :locations, format: true, 
    constraints: { format: :json } do
    collection do
      get 'query'
    end
  end
  
  get 'buildings/coord' => 'buildings#query_by_coord', format: true, 
    constraints: { format: :json }
  get 'buildings/city_company' => 'buildings#query_by_city_company', 
    format: true, constraints: { format: :json }
  get 'buildings/address_name' => 'buildings#fuzzy_query_by_address_name', 
    format: true, constraints: { format: :json }

  resources :companies, only: :index, format: true, 
    constraints: { format: :json }
  get 'companies/:name' => 'companies#query', format: true, 
    constraints: { format: :json }
  
  resources :uploads, only: :create, format: true, 
    constraints: { format: :json }

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div id="dish_summary">
  <h1>Dishes Order Summary</h1>
  <% if cart.dish_items.empty? %>
    <p>You don't have any dishes in your cart.</p>
  <% else %>
    <ol>
      <% cart.dish_items.each do |item| %>
        <% unless item.quantity > 1 %>
          <li><%= item.dish.name %></li>
        <% else %>
          <li><%= item.dish.name %> &times; <%= item.quantity %></li>
        <% end %>
        <%= link_to 'X', cart_dish_cart_item_path(cart, item), 
          method: 'delete', remote: true %><br />
      <% end %>
    </ol>
  <% end %>
</div>

<div id="combo_summary">
  <h1>Combo Order Summary</h1>
  <% if cart.combo_items.empty? %>
    <p>You don't have any combo in your cart! </p>
  <% else %>
    <ol>
      <% cart.combo_items.each do |item| %>
        <% unless item.quantity > 1 %>
          <li><%= item.catering.combo.name %></li> 
        <% else %>
          <li><%= item.catering.combo.name %> &times; <%= item.quantity %></li> 
        <% end %>
        <%= link_to 'X', cart_combo_cart_item_path(cart, item), 
          method: 'delete', remote: true %><br /> 
      <% end %>
    </ol>
  <% end %>
</div>
<p>Total price: <%= cart.total_price %></p>

app/views/carts/destroy.js.erb
$("#message").html("<%= escape_javascript(render 'layouts/messages') %>")
$("#cart_display").html("<%= escape_javascript(render @cart) %>")

app/views/carts/show.html.erb
<div id="cart_display">
  <%= render @cart %>
</div>
<%= link_to "Checkout", new_customer_order_path(current_or_guest_account) %>
<%= link_to "Clear Cart", current_cart, method: :delete, remote: true %>