config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'Account', at: 'auth', controllers: {
    omniauth_callbacks: 'account/auth_callbacks',
  }

  get 'auth/confirmation/success' => 'account/auth_callbacks#confirmation_success'
  get 'auth/password/reset' => 'account/auth_callbacks#reset_password'
  post 'chat' => 'chats#chat', constraints: { format: :xml }
  get 'chat' => 'chats#configuration'

  namespace :account, format: true, constraints: { format: :json } do
    post ':account_id/cellphone' => 'cellphones#create' 
    post ':account_id/cellphone/:id' => 'cellphones#resend'
    put ':account_id/cellphone/:id' => 'cellphones#update' 
  end

  resources :merchants, only: [:show, :update], module: :merchants, 
    format: true, constraints: { format: :json } do
    resources :dropoffs, format: true, only: [:index, :create]

    resources :restaurants, only: [:index, :create] do
      resources :caterings, only: :create

      resources :dishes, only: :create

      resources :combos, only: :create
      get 'combos/recent' => 'combos#recent'
    end

    resources :shippings, only: [:create, :update, :destroy] do
      member do
        get 'list_orders' => 'shippings#list_orders'
        put 'update_state' => 'shippings#update_state'
      end
    end

    resources :dishes, only: [:destroy, :update]

    resources :combos, only: [:destroy, :update, :show]

    resources :uploads, only: :create

    resources :debts, only: :index

    resources :transactions, only: [:index, :update, :destroy]
    get 'transactions/pending' => 'transactions#pending'

    put 'orders/:id/approve' => 'orders#approve'
    put 'orders/:id/pickup' => 'orders#pickup'
  end

  namespace :merchant, format: true, constraints: { format: :json } do
    resources :dropoffs, only: :destroy
    resources :restaurants, only: [:update, :destroy, :new]
  end
  
  resources :customers, module: :customers, format: true, 
    constraints: { format: :json } do
    resources :orders, only: [:index, :show]
    resources :combo_orders, only: [:create]
    resources :dish_orders, only: [:create]
    put 'orders/recent' => 'orders#recent'
    put 'orders/:id/cancel' => 'orders#cancel' 

    resources :payments, only: [:create, :destroy, :show, :index]
    resources :qr_codes, only: :new
  end

  resources :restaurants, module: :restaurant, only: :show, 
    format: true, constraints: { format: :json }do

    resources :dishes, only: :index

    resources :combos, only: :index

    resources :caterings, only: :index
    get 'caterings/recent' => 'caterings#recent'
  end

  namespace :restaurant, format: true, 
    constraints: { format: :json } do
    resources :caterings, only: :show

    resources :combos, only: :show

    resources :dishes, only: :show

    get 'new' => 'restaurants#new'
  end

  resources :locations, format: true, 
    constraints: { format: :json } do
    collection do
      get 'query'
    end
  end
  
  get 'buildings/coord' => 'buildings#query_by_coord', format: true, 
    constraints: { format: :json }
  get 'buildings/city_company' => 'buildings#query_by_city_company', 
    format: true, constraints: { format: :json }
  get 'buildings/address_name' => 'buildings#fuzzy_query_by_address_name', 
    format: true, constraints: { format: :json }

  resources :companies, only: :index, format: true, 
    constraints: { format: :json }
  get 'companies/:name' => 'companies#query', format: true, 
    constraints: { format: :json }
  
  resources :uploads, only: :create, format: true, 
    constraints: { format: :json }

end

app/controllers/merchants/dishes_controller.rb
class Merchant::DishesController < Merchant::MerchantController

  def create
    Dish.create! restaurant_id: @restaurant.id, image_url: @image_url, 
      name: @name, price: @price, desc: @desc
    render nothing: true, status: :created
  end

  def update
    @dish.update @image_url, @price, @name, @desc 
    render nothing: true
  end

  def destroy
    @dish.destroy
    render nothing: true
  end

  private

    def params_sanitization
      sanitize :create, merchant_id: :merchant, price: :price,
        desc: :text, restaurant_id: :restaurant, name: :name,
        image_url: :url
      sanitize :destroy, merchant_id: :merchant, id: :dish 
      sanitize :update, merchant_id: :merchant, id: :dish, 
        price: :price, desc: :text, name: :name, image_url: :url
    end

    def authorization
      authorize :create do
        @merchant.id == current_account.id && \
          @restaurant.merchant_id == @merchant.id
      end
      authorize [:update, :destroy] do
        @merchant.id == current_account.id && \
          @dish.restaurant.merchant_id == @merchant.id
      end
    end
end

app/controllers/restaurant/dishes_controller.rb
class Restaurant::DishesController < WebApplicationController

  def index
    dishes = Dish.active_by_restaurant @restaurant.id
    render json: Response::JsonResponse.new(dishes)
  end

  def show
    render json: Response::JsonResponse.new(@dish)
  end

  private

    def params_sanitization
      sanitize :index, restaurant_id: :restaurant
      sanitize :show, id: :dish 
    end

end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_combo.html.erb
<p>
  <strong> price: </strong>
  <%= combo.price %>
</p>
<p>
  <strong> image: </strong>
  <%= combo.image_url %>
</p>
<p>
  <strong> description: </strong>
  <%= combo.desc %>
</p>

app/views/dishes/_dish.html.erb
<p>
  <strong> name: </strong>
  <%= dish.name %>
</p>
<p>
  <strong> price: </strong>
  <%= dish.price %>
</p>
<p>
  <strong> image: </strong>
  <%= dish.image_url %>
</p>
<p>
  <strong> description: </strong>
  <%= dish.desc %>
</p>

<%= link_to 'Order', new_cart_item_path(dish_id: dish.id), remote: true %>
<br /><br />

app/views/dishes/_form.html.erb
<%= form_for @dish, url: restaurant_dishes_path(
                          restaurant_id: @dish.restaurant_id) do |f| %>
  <div class="field">
    <%= f.hidden_field :type, value: @dish.type %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit "Create Dish" %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing Dish</h1>

<%= render 'form' %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/index.html.erb
<h1>Listing Dishes</h1>
<% if @dishes.nil? %>
  <p>You don't have any dishes in your menu.</p>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Image url</th>
        <th>Desc</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @dishes.each do |dish| %>
        <tr>
          <td><%= dish.name %></td>
          <td><%= dish.price %></td>
          <td><%= dish.image_url %></td>
          <td><%= dish.desc %></td>
          <td><%= link_to 'Show', restaurant_dish_path(@restaurant, dish) %></td>
          <td><%= link_to 'Edit', edit_restaurant_dish_path(@restaurant, dish) %></td>
          <td><%= link_to 'Destroy', restaurant_dish_path(@restaurant, dish), 
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<%= link_to 'Add New Dish', new_restaurant_dish_path(@restaurant) %>
<%= link_to 'Back to restaurant', merchant_path(current_account) %>

app/views/dishes/new.html.erb
<h1>New Dish</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurant_dishes_path %>

app/views/dishes/show.html.erb
<p>
  <strong> name:</strong>
  <%= @dish. name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @dish.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @dish.image_url %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @dish.desc %>
</p>
<% if current_merchant.present? %>
<p>
  <strong>Count:</strong>
  <%= @dish.count %>
</p>
<% end %>

<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>